feat: enhance Postman test jobs with detailed reporting and status checks for green and blue deployments

diff --git a/.github/workflows/post-deployment.yaml b/.github/workflows/post-deployment.yaml
--- a/.github/workflows/post-deployment.yaml
+++ b/.github/workflows/post-deployment.yaml
@@ -54,7 +54,19 @@ jobs:
           newman run tests/postman/${{ inputs.project_name }}.postman_collection.json \
           -e tests/postman/${{ inputs.environment }}-green.postman_environment.json \
           --env-var "bearer_token=${{ env.TOKEN }}" \
-          --bail
+          -r cli,json \
+          --reporter-json-export tests/postman/reports/${{ inputs.environment }}-green-report.json
+        
+          # Check status codes from report
+          FAILED_REQUESTS=$(jq -r '.run.executions[] | select(.response.code >= 300 or .response.code < 200) | .item.name' newman-results.json)
+          
+          if [ ! -z "$FAILED_REQUESTS" ]; then
+            echo "Failed requests found:"
+            echo "$FAILED_REQUESTS"
+            exit 1
+          else
+            echo "All requests passed with 2xx status codes"
+          fi
 
   post-blue-deployment-tests:
     environment: ${{ inputs.environment }}
@@ -89,4 +101,16 @@ jobs:
           newman run tests/postman/${{ inputs.project_name }}.postman_collection.json \
           -e tests/postman/${{ inputs.environment }}-blue.postman_environment.json \
           --env-var "bearer_token=${{ env.TOKEN }}" \
-          --bail
+          -r cli,json \
+          --reporter-json-export tests/postman/reports/${{ inputs.environment }}-blue-report.json
+
+          # Check status codes from report
+          FAILED_REQUESTS=$(jq -r '.run.executions[] | select(.response.code >= 300 or .response.code < 200) | .item.name' newman-results.json)
+          
+          if [ ! -z "$FAILED_REQUESTS" ]; then
+            echo "Failed requests found:"
+            echo "$FAILED_REQUESTS"
+            exit 1
+          else
+            echo "All requests passed with 2xx status codes"
+          fi
